services:
  # nginx:
  #   image: jonasal/nginx-certbot
  #   ports:
  #   - "80:80"
  #   - "443:443"
  #   volumes:
  #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   - ./letsencrypt:/etc/letsencrypt
  #   environment:
  #     CERTBOT_EMAIL: ir4y.ix@gmail.com
  #   depends_on:
  #     devbox-healthcheck:
  #       condition:
  #         service_healthy
  #     frontend-healthcheck:
  #       condition:
  #         service_healthy
    nginx:
      image: nginx:latest
      ports:
        - '80:80'
      volumes:
        - ./user_conf.d:/etc/nginx/user_conf.d:ro
      depends_on:
        - frontend
        - backend
    backend:
      image: ghcr.io/projkov/fhirpath-py-as-service:3581447a60e2e6803b940f0ad025f3ff460dcc0f
      ports:
        - '5000:5000'
    frontend:
      image: ghcr.io/projkov/fhirpath-ui:35db16d8317c9f838db2120764eb9586cb9649f8
      ports:
        - '3000:3000'
      command: yarn start
