services:
  nginx:
    image: jonasal/nginx-certbot:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx:/etc/nginx/user_conf.d:ro
    - ./letsencrypt:/etc/letsencrypt
    environment:
      CERTBOT_EMAIL: prozskov@gmail.com
    depends_on:
      - frontend
      - backend
  backend:
    image: ghcr.io/projkov/fhirpath-py-as-service:3581447a60e2e6803b940f0ad025f3ff460dcc0f
    ports:
    - '5000:5000'
  frontend:
    image: ghcr.io/projkov/fhirpath-ui:1d8b3b29061bf66831a75f256b93ea0d18f1f0d4
    environment:
      REACT_APP_FHIRPATH_URL: https://api.fhirpath.me
    ports:
    - '3000:3000'
    command: yarn start
