services:
  nginx:
    image: jonasal/nginx-certbot:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx:/etc/nginx/user_conf.d:ro
    - ./letsencrypt:/etc/letsencrypt
    environment:
      CERTBOT_EMAIL: prozskov@gmail.com
    depends_on:
      - frontend
      - sage
  frontend:
    image: ghcr.io/projkov/fhirpath-ui:5aae0182736f7b3df119d5dde94306ae95329ea8
    ports:
    - '3000:80'
  sage:
    image: ghcr.io/projkov/sage:c8d670b58e39caf38fd42d1f72cbcb390c862e6e
    env_file:
      - .env-sage
    ports:
    - '3001:3000'
    command: yarn start
