services:
    backend:
      image: ghcr.io/projkov/fhirpath-py-as-service:3581447a60e2e6803b940f0ad025f3ff460dcc0f
      ports:
        - '5000:5000'
    frontend:
      image: ghcr.io/projkov/fhirpath-ui:35db16d8317c9f838db2120764eb9586cb9649f8
      ports:
        - '3000:3000'
      command: yarn start
