services:
  nginx:
    image: jonasal/nginx-certbot:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx:/etc/nginx/user_conf.d:ro
    - ./letsencrypt:/etc/letsencrypt
    environment:
      CERTBOT_EMAIL: prozskov@gmail.com
    depends_on:
      - frontend
      - backend
  backend:
    image: ghcr.io/projkov/fhirpath-py-as-service:3581447a60e2e6803b940f0ad025f3ff460dcc0f
    ports:
    - '5000:5000'
  frontend:
    image: ghcr.io/projkov/fhirpath-ui:7ffd0e221a8e413c0efdb0f6febecda8a3a56f8c
    env_file:
      - .env
    ports:
    - '3000:3000'
    command: yarn start
