name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.DIGITALOCEAN_HOST }}'
          username: '${{ secrets.DIGITALOCEAN_USERNAME }}'
          key: '${{ secrets.DIGITALOCEAN_SSH_KEY }}'
          script: |
            cd /path/to/your/app
            docker-compose pull
            docker-compose up -d

